### ISSUE TITLE
Instructor Feedback - Week 4 Hibernate 

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [kkelm/adhound#2]
Nice job getting started with Hibernate in your project!

- [ ] Does your unit test work if you run this repeatedly? I would have expected the setup method to run a process to reset the database before each test method runs. 
- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertEquals(expectedUser, actualUser);` so that you don't have to compare each instance var/column manually like this: https://github.com/kkelm/adhound/blob/c15961f496e31650a2185125466741c4f66f4fe0/src/test/java/com/adhound/persistence/UserDataTest.java#L71
- [ ] You'll likely notice, if you haven't already, that writing a Dao for each entity will be very repetitive - watch for the abstract/generic dao to be introduced in the coming week and plan to use it in your project so that you can use a single dao!

**Comment by kkelm** [comment]
Yeah, I ran into that problem of having to reset the database after each tests. As of right now I just run a command in the terminal to import the SQL file I have. I tried using your code in the videos, but since some of the SQL commands in my SQL file are on multiple lines the code throws errors. I've been looking for workarounds. Yeah, I can see how the DAO's could be reduced to fewer files.

**Comment by kkelm** [comment]
Ah, I just watched the video on a multi line SQL command in a SQL file.
